#!/usr/bin/env bash

if [ ! -f install ]; then
echo ' go install nothing to done! ' 1>&2
exit 1
fi


CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"
GOPATH="$CURDIR"

function goInstall {
    go tool vet src/$1
    function echo_fail {
        echo -e "\033[91m ------ go install $1 failed ------\033[0m"
    }
    function echo_succ {
        echo -e "\033[92m ------ go install $1 ok ------ \033[0m"
    }
    #golint src/$1
    #if [ $? != 0 ]; then
    #    echo_fail $1
    #    return
    #fi
    go install $1
    if [ $? -eq 0 ]; then
        echo_succ $1
    else
        echo_fail $1
    fi
}


goInstall mytest
goInstall webtest

